name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  api-env-check:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: api
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
      - run: npm ci
      - run: npm run lint:env

  build-panels:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        panel: [painel-admin, painel-medico, painel-secretaria, painel-funcionario, painel-login]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
      - run: npm ci
        working-directory: ${{ matrix.panel }}
      - run: npm run build --if-present
        working-directory: ${{ matrix.panel }}

