name: Build Panels

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  build:
    name: Build ${{ matrix.dir }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        dir:
          - painel-admin
          - painel-funcionario
          - painel-login
          - painel-secretaria
    defaults:
      run:
        working-directory: ${{ matrix.dir }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20.19.1'
          cache: 'npm'
          cache-dependency-path: ${{ matrix.dir }}/package-lock.json

      - name: Install dependencies
        run: |
          if [ -f package-lock.json ]; then
            npm ci
          else
            npm install
          fi

      - name: Build
        run: npm run build

  build-medico:
    name: Build painel-medico (best-effort)
    runs-on: ubuntu-latest
    continue-on-error: true
    defaults:
      run:
        working-directory: painel-medico
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20.19.1'
          cache: 'npm'
          cache-dependency-path: painel-medico/package-lock.json

      - name: Install dependencies (skip scripts)
        run: |
          if [ -f package-lock.json ]; then
            npm ci --ignore-scripts
          else
            npm install --ignore-scripts
          fi

      - name: Build shared package
        run: |
          cd packages/shared
          npm ci
          npm run build
          npm run build:types
          cd -

      - name: Build app only
        run: npm run build
